import { BottomNav, Navbar } from "@/components";
import { AuthProvider } from "@/hooks/useAuth";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-primary`}>
        <AntdRegistry>
          <div className="flex min-h-screen flex-col items-center justify-between">
            <div className="w-full max-w-md flex-grow flex flex-col">
              <AuthProvider>
                <Providers>
                  <Navbar />
                  <BottomNav>{children}</BottomNav>
                </Providers>
              </AuthProvider>
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
